POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}

###

@authorizationToken = {{response.body.authorizationToken}}

GET http://localhost:3000/api/users
Authorization: Bearer {{authorizationToken}}

###
POST http://localhost:3000/api/login
Authorization: Bearer {{authorizationToken}}
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
    "display_name": "Juan Perez",
    "email": "juan.perez@example.com"
}