### Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "user_name": "admin",
    "password": "1234"
}

### ⬆ Copiá el authorizationToken de la respuesta y pegalo abajo
@authorizationToken = fc8a5d40589a0aa10333528834927e1901094e09ea04a02bda3b7ba5149eb707
@username = nuevo_usuario

### GET - Listar todos los usuarios
GET http://localhost:3000/api/users
Authorization: Bearer {{authorizationToken}}

###

### GET - Obtener un usuario por username
GET http://localhost:3000/api/users/{{username}}
Authorization: Bearer {{authorizationToken}}

###

### POST - Crear usuario
POST http://localhost:3000/api/users
Authorization: Bearer {{authorizationToken}}
Content-Type: application/json

{
    "user_name": "Kevin",
    "password": "segura123",
    "display_name": "Nuevo Usuario",
    "email": "kevin@gmail.com",
    "role": "user"
}

###

### PATCH - Modificar usuario por username
PATCH http://localhost:3000/api/users/{{username}}
Authorization: Bearer {{authorizationToken}}
Content-Type: application/json

{
    "display_name": "Nombre Actualizado"
}

###

### DELETE - Eliminar usuario por username
DELETE http://localhost:3000/api/users/{{username}}
Authorization: Bearer {{authorizationToken}}

###

### Logout
POST http://localhost:3000/api/logout
Authorization: Bearer {{authorizationToken}}