GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Alice",
    "password": "1234"
}  

###

PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "Lucas",
    "password": "5432"
}

###

DELETE http://localhost:3000/api/users/2